version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  api-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    resource_class: small
    docker:
      # Primary container image where all commands run
      - image: cimg/base:stable

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - setup_remote_docker:
          # https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.11
      - run:
          name: "Run Tests"
          command: |
            cd experiment_api
            make docker-test
  api-deploy-dev:
    resource_class: small
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-cli/setup
      - run:
          name: "Deploy to Dev"
          command: |
            pip install ecs-deploy slack_sdk
            curl -sL https://sentry.io/get-cli/ | bash
            cd experiment_api
            make api-deploy

  api-deploy-stage:
    resource_class: small
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - aws-cli/setup
      - run:
          name: "Bump release candidates tags for release branches"
          command: |
            pip install -q semver gitpython
            python ../infrastructure/make-utils/bin/release_candidate_tags.py -b $CIRCLE_BRANCH
      - run:
          name: "Deploy to Stage"
          command: |
            cd experiment_api
            pip install ecs-deploy slack_sdk
            curl -sL https://sentry.io/get-cli/ | bash
            ../infrastructure/make-utils/bin/deploy_release_branch.sh
            

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  api-workflow:
    jobs:
      - api-test:
          context: aws
      - api-deploy-dev:
          context: aws
          requires:
              - api-test
          filters:
            branches:
              only:
                - develop
      - api-deploy-stage:
          context: stage
          requires:
              - api-test
          filters:
            branches:
              only:
                - /^api\/release\/\d+\.\d+\.\d+[a-z]*$/
